parking-v0:
  n_timesteps: !!float 2e5
  policy: 'MlpPolicy'
  model_class: 'tqc'
  n_sampled_goal: 4
  goal_selection_strategy: 'future'
  buffer_size: 1000000
  batch_size: 1024
  gamma: 0.95
  learning_rate: !!float 1e-3
  tau: 0.05
  policy_kwargs: "dict(n_critics=2, net_arch=[256, 256])"
  online_sampling: True
  max_episode_length: 100
  # normalize: True