Humanoid-v0:
  n_timesteps: !!float 1500000
  policy: 'MlpPolicy'
  learning_rate: lin_7.3e-4
  buffer_size: 300000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.98
  tau: 0.02
  train_freq: 1
  gradient_steps: 1
  learning_starts: 1000
  top_quantiles_to_drop_per_net: 5
  use_sde: True
#  policy_kwargs: "dict(log_std_init=-3, net_arch=[400, 300])"
  policy_kwargs: "dict(log_std_init=-3, net_arch=[64, 64])"
